---
title: "p8105_hw2_hn2339"
author: "Haowei Ni"
date: "2018/10/7"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
```

## Question 1 

```{r}
library(p8105.datasets)
    data(brfss_smart2010) 
    # clean the name to lower case
    BRFSS = janitor::clean_names(brfss_smart2010) %>% 
    # focus on overall health and 2002 
    filter(topic == "Overall Health") %>%
    mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>%
    filter(year == "2002") %>%
    # find state observed in seven locations 
    group_by(locationabbr, locationdesc) %>%
    summarize(number = n()) %>%
    group_by(locationabbr) %>%
    summarize(number = n()) %>%
    filter(number == 7)
    #CT, FL, NC
```
The states that are observed at seven places are CT, FL, NC 
```{r}
library(p8105.datasets)
    data(brfss_smart2010) 
    # clean the name to lower case
    observation = janitor::clean_names(brfss_smart2010) %>% 
    # focus on overall health 
    filter(topic == "Overall Health") %>%
    mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>%
    group_by(year, locationabbr) %>%
    summarize(number = n())
    #make the spaghetti plot 
    ggplot(data = observation, aes(x = year, y = number, group = locationabbr)) +
      geom_line()
```

```{r}
library(p8105.datasets)
    data(brfss_smart2010) 
    # clean the name to lower case
    excellent_table = janitor::clean_names(brfss_smart2010) %>% 
    # focus on overall health 
    filter(topic == "Overall Health") %>%
    mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>%
    group_by(locationabbr) %>%
    #filter to only NY and year 2002, 2006, 2010 
    filter(locationabbr == "NY") %>%
    filter(year == "2002" | year == "2006" | year == "2010") %>%
    select(-c(class, topic, question, sample_size, confidence_limit_low:geo_location)) %>%
    spread(key = response, value = data_value) %>%
    #make table 
    group_by(year) %>%
    summarize(mean_excellent = mean(Excellent),
              sd_excellent = sd(Excellent),
              )
```

```{r}
library(p8105.datasets)
    data(brfss_smart2010) 
    # clean the name to lower case
    five_panel = janitor::clean_names(brfss_smart2010) %>% 
    # focus on overall health 
    filter(topic == "Overall Health") %>%
    mutate(response = forcats::fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>%
    group_by(year, locationabbr) %>% 
    select(-c(class, topic, question, sample_size, confidence_limit_low:geo_location)) %>%
    spread(key = response, value = data_value) %>%
    summarize(mean_excellent = mean(Excellent ),
              mean_fair = mean(Fair),
              mean_good = mean(Good),
              mean_verygood = mean(`Very good`),
              mean_poor = mean(Poor)) %>%
    gather(key = mean_value, value = mean_proportion, mean_excellent : mean_poor)
```

    
  


## Question 2 

```{r}
library(p8105.datasets)
    data(instacart) 
    instacart = janitor::clean_names(instacart)
```

## Question 3 

```{r}
library(p8105.datasets)
    data(ny_noaa) 
    ny_noaa = janitor::clean_names(ny_noaa)
```

